on: 
  pull_request:
    branches: [master]
    types: [synchronize, opened, reopened, ready_for_review]


name: Review App Testing
jobs:
  review-app-test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Check Review deploy status
        id: reviewapp_deploy_status
        uses: niteoweb/reviewapps-deploy-status@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
